[workspace]
resolver = "2"
members = [
    "bucket",
    "cns", # Cere Name System
]

# Needed until https://github.com/paritytech/ink/issues/364 is resolved.
[profile.release]
overflow-checks = false
[profile.dev]
overflow-checks = false
