[workspace]
resolver = "2"
members = [
    "bucket",
    "cluster",
    "payments",
]

# Needed until https://github.com/paritytech/ink/issues/364 is resolved.
[profile.release]
overflow-checks = false
