// todo: introduce Dotenv

const ACTOR_SEED = "//Alice";

const EXPLORER_URL = "https://explorer.cere.network";
const DDC_BUCKET_CONTRACT_NAME = "ddc_bucket";
const DDC_NFT_REGISTRY_CONTRACT_NAME = "ddc_nft_registry";

const DEVNET_RPC_ENDPOINT = "wss://archive.devnet.cere.network/ws/";
const DEVNET_DDC_BUCKET_ADDR = "6TCrAcm51jYJwNbEc7zYFBvuBaPru9B1cAkU4PpgoTpTy9VZ";
const DEVNET_DDC_NFT_REGISTRY_ADDR = "6V1Bf84xDSRWBHjWS3PQCqVJeaJx5imPKGBnnr7WJXUUVGBi";
const DEVNET_CHAIN_NAME = "Cere Devnet";

const TESTNET_RPC_ENDPOINT = "wss://archive.devnet.cere.network/ws/";
const TESTNET_DDC_BUCKET_ADDR = "6TyNotWczZXMaXkF6mJ2cBMS6e1hgu5hFYuTpfg9vtH35gu3";
const TESTNET_DDC_NFT_REGISTRY_ADDR = "6VFZJT9Kox8iZN4DL27GNFCpfTWHXbDst2WC7jpiJXv36eGR";
const TESTNET_CHAIN_NAME = "Cere Testnet";

const LOCAL_RPC_ENDPOINT = "ws://127.0.0.1:9944/";
const LOCAL_DDC_BUCKET_ADDR = ""; // add your local address
const LOCAL_DDC_NFT_REGISTRY_ADDR = "";
const LOCAL_CHAIN_NAME = "Development";

module.exports = {
  ACTOR_SEED,
  EXPLORER_URL,

  DDC_BUCKET_CONTRACT_NAME,
  DDC_NFT_REGISTRY_CONTRACT_NAME,

  DEVNET_RPC_ENDPOINT,
  DEVNET_DDC_BUCKET_ADDR,
  DEVNET_DDC_NFT_REGISTRY_ADDR,
  DEVNET_CHAIN_NAME,

  TESTNET_RPC_ENDPOINT,
  TESTNET_DDC_BUCKET_ADDR,
  TESTNET_DDC_NFT_REGISTRY_ADDR,
  TESTNET_CHAIN_NAME,

  LOCAL_RPC_ENDPOINT,
  LOCAL_DDC_BUCKET_ADDR,
  LOCAL_DDC_NFT_REGISTRY_ADDR,
  LOCAL_CHAIN_NAME
}